::: lineapy.exceptions.user_exception
